// Generated by CoffeeScript 1.10.0
var checkServer, currentScene, draw, setup, socket;

currentScene = 0;

socket = io('http://localhost:3000');

checkServer = function() {
  return console.log("checking server...");
};

setup = function() {
  return createCanvas(window.innerWidth, window.innerHeight);
};

draw = function() {
  background(0);
  fill(255, 0, 0);
  return ellipse(mouseX, mouseY, 40, 40);
};

setInterval(checkServer, 1000);

//# sourceMappingURL=client.js.map
