// Generated by CoffeeScript 1.10.0
var bDebug, checkServer, draw, mousePressed, setup, sharedData, socket;

sharedData = [];

socket = io('http://localhost:3000');

bDebug = true;

checkServer = function() {
  socket.emit('hello', 'ping!');
  return console.log("pinging server...");
};

setup = function() {
  return createCanvas(window.innerWidth, window.innerHeight);
};

draw = function() {
  background(0);
  fill(255, 0, 0);
  ellipse(mouseX, mouseY, 40, 40);
  if (bDebug) {
    fill(255);
    return text("Current Scene " + sharedData.currentScene, 0, 10);
  }
};

mousePressed = function() {
  return socket.emit("hello", "HI HI HI");
};

socket.on('pingback', function(data) {
  console.log(data.testString);
  return sharedData = data;
});

setInterval(checkServer, 1000);

//# sourceMappingURL=client.js.map
