// Generated by CoffeeScript 1.10.0
var clientIDs, connectedUsers, handleCheck, handleHello, io, keypress, server, setScene, sharedData;

server = require('http').createServer();

io = require('socket.io')(server);

keypress = require('keypress');

keypress(process.stdin);

clientIDs = [];

sharedData = {
  currentScene: 0,
  testString: "testThing"
};

connectedUsers = 0;

handleHello = function(data) {
  console.log("hello " + data);
  console.log(this.id);
  return io.sockets.sockets[this.id].emit('pingback', sharedData);
};

handleCheck = function(data) {
  console.log("check in");
  io.sockets.sockets[this.id].emit('pingback', sharedData);
  return console.log(this.id(+" pinged."));
};

io.on('connection', function(socket) {
  connectedUsers++;
  clientIDs.push(socket.id);
  console.log("user connected! " + connectedUsers + " connected. ID= " + socket.id);
  socket.on('hello', handleHello);
  return socket.on('disconnect', function() {
    connectedUsers--;
    return console.log("disconnected... " + connectedUsers + " left.");
  });
});

setScene = function(newScene) {
  sharedData.currentScene = newScene;
  console.log("set scene " + newScene);
  return io.emit('pingback', sharedData);
};

process.stdin.on('keypress', function(ch, key) {
  console.log('got keypress ', key);
  if (key && key.ctrl && key.name === 'c') {
    return process.stdin.pause();
  } else if (key && key.name === 'q') {
    return setScene(1);
  } else if (key && key.name === 'w') {
    return setScene(2);
  }
});

process.stdin.setRawMode(true);

process.stdin.resume();

server.listen(3000);

console.log("running...");

//# sourceMappingURL=medeaServer.js.map
